<?php
/**
 * @var  \Findomestic\MagentoRedirectPay\Block\Checkout\Failure $block
 */
?>
<div id="findomestic-success" class="findomestic-failure">
    <div class="findomestic-success-title">
        <div class="findomestic-success-title-col findomestic-success-title-img">
            <img id="eps" src="<?php echo $block->getLogo(); ?>" alt="Findomestic" />
        </div>
    </div>
    <p>
        Ci dispiace, non possiamo accettare la tua richiesta. Puoi riempire di nuovo il tuo carrello e procedere con un altro metodo di pagamento.
    </p>
</div>
<!--<h3>Pratica non accettata, ordine annullato.</h3>-->
